Project5: Proj5main.o island.o 
	g++ -o Project5 Proj5main.o island.o

Proj5main.o: list.h island.h
	g++ -c Proj5main.cpp

island.o: island.cpp island.h
	g++ -c island.cpp

c:
	rm Proj5main.o island.o p5