buildselection:
	rm -f selectionsort.exe
	g++ -g -std=c++11 -Wall selectionsort.cpp util.cpp -o selectionsort.exe
	
runselection:
	./selectionsort.exe

buildmerge:
	rm -f mergesort.exe
	g++ -g -std=c++11 -Wall mergesort.cpp util.cpp -o mergesort.exe
	
runmerge:
	./mergesort.exe
