Project6: Proj6main.o island.o 
	g++ -o Project6 Proj6main.o island.o

Proj6main.o: list.h island.h myQueue.h myStack.h Proj6main.cpp
	g++ -c Proj6main.cpp

island.o: island.cpp island.h
	g++ -c island.cpp

c:
	rm p6main.o island.o Project6
